definitions:
  common_env: &common_env
    flutter: 3.35.4
    java: 17



workflows:
  android-development:
    name: Android Development
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      <<: *common_env

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build Development APK
        script: |
          flutter build apk \
            --flavor development \
            --dart-define-from-file=dart_defines/development.json

    cache:
      cache_paths:
        - ~/.pub-cache
        - $HOME/.gradle/caches

    artifacts:
      - build/**/outputs/**/*.apk

  android-staging:
    name: Android Staging
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      <<: *common_env

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build Staging APK
        script: |
          flutter build apk \
            --flavor staging \
            --dart-define-from-file=dart_defines/staging.json

    cache:
      cache_paths:
        - ~/.pub-cache
        - $HOME/.gradle/caches

    artifacts:
      - build/**/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - fakharany00@gmail.com
        notify:
          success: true
          failure: true

  android-production:
    name: Android Production
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      <<: *common_env
      android_signing:
        - flav_prod_keystore

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build Production AAB
        script: |
          flutter build appbundle \
            --release \
            --flavor production \
            --dart-define-from-file=dart_defines/production.json

    cache:
      cache_paths:
        - ~/.pub-cache
        - $HOME/.gradle/caches

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt

  ios-development:
    name: iOS Development
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      <<: *common_env


  ios-staging:
    name: iOS Staging
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      <<: *common_env


  ios-production:
    name: iOS Production
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      <<: *common_env